sudo: required
services:
  - docker

before_install:
  - docker build -t avishekbaruafin/docker-react -f Dockerfile.dev .

script:
  - docker run avishekbaruafin/docker-react npm run test -- --coverage
